// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createClasses = `-- name: CreateClasses :batchexec
INSERT INTO scry_quest.classes (name, description, hit_die, primary_ability, saving_throw_proficiencies, skill_proficiencies, embedding, embedding_model, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    hit_die = EXCLUDED.hit_die,
    primary_ability = EXCLUDED.primary_ability,
    saving_throw_proficiencies = EXCLUDED.saving_throw_proficiencies,
    skill_proficiencies = EXCLUDED.skill_proficiencies,
    embedding = EXCLUDED.embedding,
    embedding_model = EXCLUDED.embedding_model,
    raw_data = EXCLUDED.raw_data,
    updated_at = NOW()
`

type CreateClassesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateClassesParams struct {
	Name                     string          `json:"name"`
	Description              pgtype.Text     `json:"description"`
	HitDie                   pgtype.Int4     `json:"hit_die"`
	PrimaryAbility           pgtype.Text     `json:"primary_ability"`
	SavingThrowProficiencies pgtype.Text     `json:"saving_throw_proficiencies"`
	SkillProficiencies       []string        `json:"skill_proficiencies"`
	Embedding                pgvector.Vector `json:"embedding"`
	EmbeddingModel           pgtype.Text     `json:"embedding_model"`
	RawData                  []byte          `json:"raw_data"`
}

func (q *Queries) CreateClasses(ctx context.Context, arg []CreateClassesParams) *CreateClassesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Name,
			a.Description,
			a.HitDie,
			a.PrimaryAbility,
			a.SavingThrowProficiencies,
			a.SkillProficiencies,
			a.Embedding,
			a.EmbeddingModel,
			a.RawData,
		}
		batch.Queue(createClasses, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateClassesBatchResults{br, len(arg), false}
}

func (b *CreateClassesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateClassesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createCreatures = `-- name: CreateCreatures :batchexec
INSERT INTO scry_quest.bestiary (name, size, type, subtype, alignment, armor_class, hit_points, hit_dice, speed, abilities, skills, senses, languages, challenge_rating, embedding, embedding_model, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (name) DO UPDATE SET
    size = EXCLUDED.size,
    type = EXCLUDED.type,
    subtype = EXCLUDED.subtype,
    alignment = EXCLUDED.alignment,
    armor_class = EXCLUDED.armor_class,
    hit_points = EXCLUDED.hit_points,
    hit_dice = EXCLUDED.hit_dice,
    speed = EXCLUDED.speed,
    abilities = EXCLUDED.abilities,
    skills = EXCLUDED.skills,
    senses = EXCLUDED.senses,
    languages = EXCLUDED.languages,
    challenge_rating = EXCLUDED.challenge_rating,
    embedding = EXCLUDED.embedding,
    embedding_model = EXCLUDED.embedding_model,
    raw_data = EXCLUDED.raw_data,
    updated_at = NOW()
`

type CreateCreaturesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateCreaturesParams struct {
	Name            string          `json:"name"`
	Size            pgtype.Text     `json:"size"`
	Type            pgtype.Text     `json:"type"`
	Subtype         pgtype.Text     `json:"subtype"`
	Alignment       pgtype.Text     `json:"alignment"`
	ArmorClass      pgtype.Int4     `json:"armor_class"`
	HitPoints       pgtype.Int4     `json:"hit_points"`
	HitDice         pgtype.Text     `json:"hit_dice"`
	Speed           []byte          `json:"speed"`
	Abilities       []byte          `json:"abilities"`
	Skills          []byte          `json:"skills"`
	Senses          pgtype.Text     `json:"senses"`
	Languages       pgtype.Text     `json:"languages"`
	ChallengeRating pgtype.Text     `json:"challenge_rating"`
	Embedding       pgvector.Vector `json:"embedding"`
	EmbeddingModel  pgtype.Text     `json:"embedding_model"`
	RawData         []byte          `json:"raw_data"`
}

func (q *Queries) CreateCreatures(ctx context.Context, arg []CreateCreaturesParams) *CreateCreaturesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Name,
			a.Size,
			a.Type,
			a.Subtype,
			a.Alignment,
			a.ArmorClass,
			a.HitPoints,
			a.HitDice,
			a.Speed,
			a.Abilities,
			a.Skills,
			a.Senses,
			a.Languages,
			a.ChallengeRating,
			a.Embedding,
			a.EmbeddingModel,
			a.RawData,
		}
		batch.Queue(createCreatures, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateCreaturesBatchResults{br, len(arg), false}
}

func (b *CreateCreaturesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateCreaturesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createSpeciesBatch = `-- name: CreateSpeciesBatch :batchexec
INSERT INTO scry_quest.species (name, description, size, speed, ability_score_increase, traits, embedding, embedding_model, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    size = EXCLUDED.size,
    speed = EXCLUDED.speed,
    ability_score_increase = EXCLUDED.ability_score_increase,
    traits = EXCLUDED.traits,
    embedding = EXCLUDED.embedding,
    embedding_model = EXCLUDED.embedding_model,
    raw_data = EXCLUDED.raw_data,
    updated_at = NOW()
`

type CreateSpeciesBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateSpeciesBatchParams struct {
	Name                 string          `json:"name"`
	Description          pgtype.Text     `json:"description"`
	Size                 pgtype.Text     `json:"size"`
	Speed                pgtype.Int4     `json:"speed"`
	AbilityScoreIncrease []byte          `json:"ability_score_increase"`
	Traits               []string        `json:"traits"`
	Embedding            pgvector.Vector `json:"embedding"`
	EmbeddingModel       pgtype.Text     `json:"embedding_model"`
	RawData              []byte          `json:"raw_data"`
}

func (q *Queries) CreateSpeciesBatch(ctx context.Context, arg []CreateSpeciesBatchParams) *CreateSpeciesBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Name,
			a.Description,
			a.Size,
			a.Speed,
			a.AbilityScoreIncrease,
			a.Traits,
			a.Embedding,
			a.EmbeddingModel,
			a.RawData,
		}
		batch.Queue(createSpeciesBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateSpeciesBatchBatchResults{br, len(arg), false}
}

func (b *CreateSpeciesBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateSpeciesBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createSpells = `-- name: CreateSpells :batchexec
INSERT INTO scry_quest.spells (name, description, level, school, casting_time, range_value, components, duration, classes, embedding, embedding_model, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    level = EXCLUDED.level,
    school = EXCLUDED.school,
    casting_time = EXCLUDED.casting_time,
    range_value = EXCLUDED.range_value,
    components = EXCLUDED.components,
    duration = EXCLUDED.duration,
    classes = EXCLUDED.classes,
    embedding = EXCLUDED.embedding,
    embedding_model = EXCLUDED.embedding_model,
    raw_data = EXCLUDED.raw_data,
    updated_at = NOW()
`

type CreateSpellsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateSpellsParams struct {
	Name           string          `json:"name"`
	Description    pgtype.Text     `json:"description"`
	Level          int32           `json:"level"`
	School         pgtype.Text     `json:"school"`
	CastingTime    pgtype.Text     `json:"casting_time"`
	RangeValue     pgtype.Text     `json:"range_value"`
	Components     pgtype.Text     `json:"components"`
	Duration       pgtype.Text     `json:"duration"`
	Classes        []string        `json:"classes"`
	Embedding      pgvector.Vector `json:"embedding"`
	EmbeddingModel pgtype.Text     `json:"embedding_model"`
	RawData        []byte          `json:"raw_data"`
}

func (q *Queries) CreateSpells(ctx context.Context, arg []CreateSpellsParams) *CreateSpellsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Name,
			a.Description,
			a.Level,
			a.School,
			a.CastingTime,
			a.RangeValue,
			a.Components,
			a.Duration,
			a.Classes,
			a.Embedding,
			a.EmbeddingModel,
			a.RawData,
		}
		batch.Queue(createSpells, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateSpellsBatchResults{br, len(arg), false}
}

func (b *CreateSpellsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateSpellsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
