// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: creatures.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createCreature = `-- name: CreateCreature :one
INSERT INTO scry_quest.bestiary (name, size, type, subtype, alignment, armor_class, hit_points, hit_dice, speed, abilities, skills, senses, languages, challenge_rating, embedding, embedding_model, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, name, size, type, subtype, alignment, armor_class, hit_points, hit_dice, speed, abilities, skills, senses, languages, challenge_rating, embedding, raw_data, created_at, updated_at, embedding_model
`

type CreateCreatureParams struct {
	Name            string          `json:"name"`
	Size            pgtype.Text     `json:"size"`
	Type            pgtype.Text     `json:"type"`
	Subtype         pgtype.Text     `json:"subtype"`
	Alignment       pgtype.Text     `json:"alignment"`
	ArmorClass      pgtype.Int4     `json:"armor_class"`
	HitPoints       pgtype.Int4     `json:"hit_points"`
	HitDice         pgtype.Text     `json:"hit_dice"`
	Speed           []byte          `json:"speed"`
	Abilities       []byte          `json:"abilities"`
	Skills          []byte          `json:"skills"`
	Senses          pgtype.Text     `json:"senses"`
	Languages       pgtype.Text     `json:"languages"`
	ChallengeRating pgtype.Text     `json:"challenge_rating"`
	Embedding       pgvector.Vector `json:"embedding"`
	EmbeddingModel  pgtype.Text     `json:"embedding_model"`
	RawData         []byte          `json:"raw_data"`
}

func (q *Queries) CreateCreature(ctx context.Context, arg CreateCreatureParams) (ScryQuestBestiary, error) {
	row := q.db.QueryRow(ctx, createCreature,
		arg.Name,
		arg.Size,
		arg.Type,
		arg.Subtype,
		arg.Alignment,
		arg.ArmorClass,
		arg.HitPoints,
		arg.HitDice,
		arg.Speed,
		arg.Abilities,
		arg.Skills,
		arg.Senses,
		arg.Languages,
		arg.ChallengeRating,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.RawData,
	)
	var i ScryQuestBestiary
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.Type,
		&i.Subtype,
		&i.Alignment,
		&i.ArmorClass,
		&i.HitPoints,
		&i.HitDice,
		&i.Speed,
		&i.Abilities,
		&i.Skills,
		&i.Senses,
		&i.Languages,
		&i.ChallengeRating,
		&i.Embedding,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingModel,
	)
	return i, err
}

const deleteBeast = `-- name: DeleteBeast :exec
DELETE FROM scry_quest.bestiary WHERE id = $1
`

func (q *Queries) DeleteBeast(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBeast, id)
	return err
}

const getBeastByID = `-- name: GetBeastByID :one
SELECT id, name, size, type, subtype, alignment, armor_class, hit_points, hit_dice, speed, abilities, skills, senses, languages, challenge_rating, embedding, raw_data, created_at, updated_at, embedding_model FROM scry_quest.bestiary WHERE id = $1
`

func (q *Queries) GetBeastByID(ctx context.Context, id pgtype.UUID) (ScryQuestBestiary, error) {
	row := q.db.QueryRow(ctx, getBeastByID, id)
	var i ScryQuestBestiary
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.Type,
		&i.Subtype,
		&i.Alignment,
		&i.ArmorClass,
		&i.HitPoints,
		&i.HitDice,
		&i.Speed,
		&i.Abilities,
		&i.Skills,
		&i.Senses,
		&i.Languages,
		&i.ChallengeRating,
		&i.Embedding,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingModel,
	)
	return i, err
}

const getBeastByName = `-- name: GetBeastByName :one
SELECT id, name, size, type, subtype, alignment, armor_class, hit_points, hit_dice, speed, abilities, skills, senses, languages, challenge_rating, embedding, raw_data, created_at, updated_at, embedding_model FROM scry_quest.bestiary WHERE name = $1
`

func (q *Queries) GetBeastByName(ctx context.Context, name string) (ScryQuestBestiary, error) {
	row := q.db.QueryRow(ctx, getBeastByName, name)
	var i ScryQuestBestiary
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.Type,
		&i.Subtype,
		&i.Alignment,
		&i.ArmorClass,
		&i.HitPoints,
		&i.HitDice,
		&i.Speed,
		&i.Abilities,
		&i.Skills,
		&i.Senses,
		&i.Languages,
		&i.ChallengeRating,
		&i.Embedding,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingModel,
	)
	return i, err
}

const listBeasts = `-- name: ListBeasts :many
SELECT id, name, size, type, subtype, alignment, armor_class, hit_points, hit_dice, speed, abilities, skills, senses, languages, challenge_rating, embedding, raw_data, created_at, updated_at, embedding_model FROM scry_quest.bestiary
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListBeastsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBeasts(ctx context.Context, arg ListBeastsParams) ([]ScryQuestBestiary, error) {
	rows, err := q.db.Query(ctx, listBeasts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScryQuestBestiary{}
	for rows.Next() {
		var i ScryQuestBestiary
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.Type,
			&i.Subtype,
			&i.Alignment,
			&i.ArmorClass,
			&i.HitPoints,
			&i.HitDice,
			&i.Speed,
			&i.Abilities,
			&i.Skills,
			&i.Senses,
			&i.Languages,
			&i.ChallengeRating,
			&i.Embedding,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeastsByChallengeRating = `-- name: ListBeastsByChallengeRating :many
SELECT id, name, size, type, subtype, alignment, armor_class, hit_points, hit_dice, speed, abilities, skills, senses, languages, challenge_rating, embedding, raw_data, created_at, updated_at, embedding_model FROM scry_quest.bestiary
WHERE challenge_rating = $1
ORDER BY name
`

func (q *Queries) ListBeastsByChallengeRating(ctx context.Context, challengeRating pgtype.Text) ([]ScryQuestBestiary, error) {
	rows, err := q.db.Query(ctx, listBeastsByChallengeRating, challengeRating)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScryQuestBestiary{}
	for rows.Next() {
		var i ScryQuestBestiary
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.Type,
			&i.Subtype,
			&i.Alignment,
			&i.ArmorClass,
			&i.HitPoints,
			&i.HitDice,
			&i.Speed,
			&i.Abilities,
			&i.Skills,
			&i.Senses,
			&i.Languages,
			&i.ChallengeRating,
			&i.Embedding,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeastsByType = `-- name: ListBeastsByType :many
SELECT id, name, size, type, subtype, alignment, armor_class, hit_points, hit_dice, speed, abilities, skills, senses, languages, challenge_rating, embedding, raw_data, created_at, updated_at, embedding_model FROM scry_quest.bestiary
WHERE type = $1
ORDER BY name
`

func (q *Queries) ListBeastsByType(ctx context.Context, type_ pgtype.Text) ([]ScryQuestBestiary, error) {
	rows, err := q.db.Query(ctx, listBeastsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScryQuestBestiary{}
	for rows.Next() {
		var i ScryQuestBestiary
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.Type,
			&i.Subtype,
			&i.Alignment,
			&i.ArmorClass,
			&i.HitPoints,
			&i.HitDice,
			&i.Speed,
			&i.Abilities,
			&i.Skills,
			&i.Senses,
			&i.Languages,
			&i.ChallengeRating,
			&i.Embedding,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCreaturesByEmbedding = `-- name: SearchCreaturesByEmbedding :many
SELECT 
    id,
    name,
    size,
    type,
    alignment,
    challenge_rating,
    embedding_model,
    (1 - (embedding <=> $1))::float8 as similarity
FROM scry_quest.bestiary
WHERE embedding IS NOT NULL
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchCreaturesByEmbeddingParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	Limit     int32           `json:"limit"`
}

type SearchCreaturesByEmbeddingRow struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Size            pgtype.Text `json:"size"`
	Type            pgtype.Text `json:"type"`
	Alignment       pgtype.Text `json:"alignment"`
	ChallengeRating pgtype.Text `json:"challenge_rating"`
	EmbeddingModel  pgtype.Text `json:"embedding_model"`
	Similarity      float64     `json:"similarity"`
}

func (q *Queries) SearchCreaturesByEmbedding(ctx context.Context, arg SearchCreaturesByEmbeddingParams) ([]SearchCreaturesByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchCreaturesByEmbedding, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCreaturesByEmbeddingRow{}
	for rows.Next() {
		var i SearchCreaturesByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.Type,
			&i.Alignment,
			&i.ChallengeRating,
			&i.EmbeddingModel,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreatureEmbedding = `-- name: UpdateCreatureEmbedding :exec
UPDATE scry_quest.bestiary 
SET embedding = $2, embedding_model = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateCreatureEmbeddingParams struct {
	ID             pgtype.UUID     `json:"id"`
	Embedding      pgvector.Vector `json:"embedding"`
	EmbeddingModel pgtype.Text     `json:"embedding_model"`
}

func (q *Queries) UpdateCreatureEmbedding(ctx context.Context, arg UpdateCreatureEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateCreatureEmbedding, arg.ID, arg.Embedding, arg.EmbeddingModel)
	return err
}
