// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: embeddings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countItemsByEmbeddingModel = `-- name: CountItemsByEmbeddingModel :many
SELECT 
    'spells' as table_name,
    COALESCE(embedding_model, 'no_embedding') as model,
    COUNT(*) as count
FROM scry_quest.spells
GROUP BY embedding_model

UNION ALL

SELECT 
    'bestiary' as table_name,
    COALESCE(embedding_model, 'no_embedding') as model,
    COUNT(*) as count
FROM scry_quest.bestiary
GROUP BY embedding_model

UNION ALL

SELECT 
    'classes' as table_name,
    COALESCE(embedding_model, 'no_embedding') as model,
    COUNT(*) as count
FROM scry_quest.classes
GROUP BY embedding_model

UNION ALL

SELECT 
    'species' as table_name,
    COALESCE(embedding_model, 'no_embedding') as model,
    COUNT(*) as count
FROM scry_quest.species
GROUP BY embedding_model

ORDER BY table_name, model
`

type CountItemsByEmbeddingModelRow struct {
	TableName string `json:"table_name"`
	Model     string `json:"model"`
	Count     int64  `json:"count"`
}

func (q *Queries) CountItemsByEmbeddingModel(ctx context.Context) ([]CountItemsByEmbeddingModelRow, error) {
	rows, err := q.db.Query(ctx, countItemsByEmbeddingModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountItemsByEmbeddingModelRow{}
	for rows.Next() {
		var i CountItemsByEmbeddingModelRow
		if err := rows.Scan(&i.TableName, &i.Model, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteClassEmbeddings = `-- name: DeleteClassEmbeddings :exec
UPDATE scry_quest.classes 
SET embedding = NULL, embedding_model = NULL 
WHERE embedding_model = $1 OR $1 = 'all'
`

func (q *Queries) DeleteClassEmbeddings(ctx context.Context, embeddingModel pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteClassEmbeddings, embeddingModel)
	return err
}

const deleteCreatureEmbeddings = `-- name: DeleteCreatureEmbeddings :exec
UPDATE scry_quest.bestiary 
SET embedding = NULL, embedding_model = NULL 
WHERE embedding_model = $1 OR $1 = 'all'
`

func (q *Queries) DeleteCreatureEmbeddings(ctx context.Context, embeddingModel pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteCreatureEmbeddings, embeddingModel)
	return err
}

const deleteSpeciesEmbeddings = `-- name: DeleteSpeciesEmbeddings :exec
UPDATE scry_quest.species 
SET embedding = NULL, embedding_model = NULL 
WHERE embedding_model = $1 OR $1 = 'all'
`

func (q *Queries) DeleteSpeciesEmbeddings(ctx context.Context, embeddingModel pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteSpeciesEmbeddings, embeddingModel)
	return err
}

const deleteSpellEmbeddings = `-- name: DeleteSpellEmbeddings :exec
UPDATE scry_quest.spells 
SET embedding = NULL, embedding_model = NULL 
WHERE embedding_model = $1 OR $1 = 'all'
`

func (q *Queries) DeleteSpellEmbeddings(ctx context.Context, embeddingModel pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteSpellEmbeddings, embeddingModel)
	return err
}

const getClassesWithoutEmbeddings = `-- name: GetClassesWithoutEmbeddings :many
SELECT id, name, description, raw_data
FROM scry_quest.classes
WHERE embedding IS NULL
ORDER BY created_at DESC
`

type GetClassesWithoutEmbeddingsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	RawData     []byte      `json:"raw_data"`
}

func (q *Queries) GetClassesWithoutEmbeddings(ctx context.Context) ([]GetClassesWithoutEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, getClassesWithoutEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClassesWithoutEmbeddingsRow{}
	for rows.Next() {
		var i GetClassesWithoutEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RawData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesWithoutEmbeddings = `-- name: GetCreaturesWithoutEmbeddings :many
SELECT id, name, size, type, alignment, challenge_rating, raw_data
FROM scry_quest.bestiary
WHERE embedding IS NULL
ORDER BY created_at DESC
`

type GetCreaturesWithoutEmbeddingsRow struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Size            pgtype.Text `json:"size"`
	Type            pgtype.Text `json:"type"`
	Alignment       pgtype.Text `json:"alignment"`
	ChallengeRating pgtype.Text `json:"challenge_rating"`
	RawData         []byte      `json:"raw_data"`
}

func (q *Queries) GetCreaturesWithoutEmbeddings(ctx context.Context) ([]GetCreaturesWithoutEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, getCreaturesWithoutEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCreaturesWithoutEmbeddingsRow{}
	for rows.Next() {
		var i GetCreaturesWithoutEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.Type,
			&i.Alignment,
			&i.ChallengeRating,
			&i.RawData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmbeddingStats = `-- name: GetEmbeddingStats :many
SELECT table_name, total_rows, embedded_rows, embedding_model, expected_dimensions FROM scry_quest.embedding_stats ORDER BY table_name, embedding_model
`

func (q *Queries) GetEmbeddingStats(ctx context.Context) ([]ScryQuestEmbeddingStat, error) {
	rows, err := q.db.Query(ctx, getEmbeddingStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScryQuestEmbeddingStat{}
	for rows.Next() {
		var i ScryQuestEmbeddingStat
		if err := rows.Scan(
			&i.TableName,
			&i.TotalRows,
			&i.EmbeddedRows,
			&i.EmbeddingModel,
			&i.ExpectedDimensions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpeciesWithoutEmbeddings = `-- name: GetSpeciesWithoutEmbeddings :many
SELECT id, name, description, raw_data
FROM scry_quest.species
WHERE embedding IS NULL
ORDER BY created_at DESC
`

type GetSpeciesWithoutEmbeddingsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	RawData     []byte      `json:"raw_data"`
}

func (q *Queries) GetSpeciesWithoutEmbeddings(ctx context.Context) ([]GetSpeciesWithoutEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, getSpeciesWithoutEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpeciesWithoutEmbeddingsRow{}
	for rows.Next() {
		var i GetSpeciesWithoutEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RawData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsWithoutEmbeddings = `-- name: GetSpellsWithoutEmbeddings :many
SELECT id, name, description, level, school, raw_data
FROM scry_quest.spells
WHERE embedding IS NULL
ORDER BY created_at DESC
`

type GetSpellsWithoutEmbeddingsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Level       int32       `json:"level"`
	School      pgtype.Text `json:"school"`
	RawData     []byte      `json:"raw_data"`
}

func (q *Queries) GetSpellsWithoutEmbeddings(ctx context.Context) ([]GetSpellsWithoutEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, getSpellsWithoutEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpellsWithoutEmbeddingsRow{}
	for rows.Next() {
		var i GetSpellsWithoutEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Level,
			&i.School,
			&i.RawData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAllContentByEmbedding = `-- name: SearchAllContentByEmbedding :many
SELECT 
    'spell' as content_type,
    s.id::text,
    s.name,
    s.description,
    s.embedding_model,
    (1 - (s.embedding <=> $1)) as similarity
FROM scry_quest.spells s
WHERE s.embedding IS NOT NULL

UNION ALL

SELECT 
    'creature' as content_type,
    b.id::text,
    b.name,
    CONCAT(b.size, ' ', b.type, ', ', b.alignment) as description,
    b.embedding_model,
    (1 - (b.embedding <=> $1)) as similarity
FROM scry_quest.bestiary b
WHERE b.embedding IS NOT NULL

UNION ALL

SELECT 
    'class' as content_type,
    c.id::text,
    c.name,
    c.description,
    c.embedding_model,
    (1 - (c.embedding <=> $1)) as similarity
FROM scry_quest.classes c
WHERE c.embedding IS NOT NULL

UNION ALL

SELECT 
    'species' as content_type,
    sp.id::text,
    sp.name,
    sp.description,
    sp.embedding_model,
    (1 - (sp.embedding <=> $1)) as similarity
FROM scry_quest.species sp
WHERE sp.embedding IS NOT NULL

ORDER BY similarity DESC
LIMIT $2
`

type SearchAllContentByEmbeddingParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	Limit     int32           `json:"limit"`
}

type SearchAllContentByEmbeddingRow struct {
	ContentType    string      `json:"content_type"`
	SID            string      `json:"s_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	EmbeddingModel pgtype.Text `json:"embedding_model"`
	Similarity     int32       `json:"similarity"`
}

func (q *Queries) SearchAllContentByEmbedding(ctx context.Context, arg SearchAllContentByEmbeddingParams) ([]SearchAllContentByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchAllContentByEmbedding, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAllContentByEmbeddingRow{}
	for rows.Next() {
		var i SearchAllContentByEmbeddingRow
		if err := rows.Scan(
			&i.ContentType,
			&i.SID,
			&i.Name,
			&i.Description,
			&i.EmbeddingModel,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
