// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ScryQuestBestiary struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Size            pgtype.Text        `json:"size"`
	Type            pgtype.Text        `json:"type"`
	Subtype         pgtype.Text        `json:"subtype"`
	Alignment       pgtype.Text        `json:"alignment"`
	ArmorClass      pgtype.Int4        `json:"armor_class"`
	HitPoints       pgtype.Int4        `json:"hit_points"`
	HitDice         pgtype.Text        `json:"hit_dice"`
	Speed           []byte             `json:"speed"`
	Abilities       []byte             `json:"abilities"`
	Skills          []byte             `json:"skills"`
	Senses          pgtype.Text        `json:"senses"`
	Languages       pgtype.Text        `json:"languages"`
	ChallengeRating pgtype.Text        `json:"challenge_rating"`
	Embedding       pgvector.Vector    `json:"embedding"`
	RawData         []byte             `json:"raw_data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ScryQuestClass struct {
	ID                       pgtype.UUID        `json:"id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	HitDie                   pgtype.Int4        `json:"hit_die"`
	PrimaryAbility           pgtype.Text        `json:"primary_ability"`
	SavingThrowProficiencies pgtype.Text        `json:"saving_throw_proficiencies"`
	SkillProficiencies       []string           `json:"skill_proficiencies"`
	Embedding                pgvector.Vector    `json:"embedding"`
	RawData                  []byte             `json:"raw_data"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type ScryQuestSpecy struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Description          pgtype.Text        `json:"description"`
	Size                 pgtype.Text        `json:"size"`
	Speed                pgtype.Int4        `json:"speed"`
	AbilityScoreIncrease []byte             `json:"ability_score_increase"`
	Traits               []string           `json:"traits"`
	Embedding            pgvector.Vector    `json:"embedding"`
	RawData              []byte             `json:"raw_data"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ScryQuestSpell struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Level       int32              `json:"level"`
	School      pgtype.Text        `json:"school"`
	CastingTime pgtype.Text        `json:"casting_time"`
	RangeValue  pgtype.Text        `json:"range_value"`
	Components  pgtype.Text        `json:"components"`
	Duration    pgtype.Text        `json:"duration"`
	Classes     []string           `json:"classes"`
	Embedding   pgvector.Vector    `json:"embedding"`
	RawData     []byte             `json:"raw_data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
