// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountItemsByEmbeddingModel(ctx context.Context) ([]CountItemsByEmbeddingModelRow, error)
	CreateClass(ctx context.Context, arg CreateClassParams) (ScryQuestClass, error)
	CreateClasses(ctx context.Context, arg []CreateClassesParams) *CreateClassesBatchResults
	CreateCreature(ctx context.Context, arg CreateCreatureParams) (ScryQuestBestiary, error)
	CreateCreatures(ctx context.Context, arg []CreateCreaturesParams) *CreateCreaturesBatchResults
	CreateSpecies(ctx context.Context, arg CreateSpeciesParams) (ScryQuestSpecy, error)
	CreateSpeciesBatch(ctx context.Context, arg []CreateSpeciesBatchParams) *CreateSpeciesBatchBatchResults
	CreateSpell(ctx context.Context, arg CreateSpellParams) (ScryQuestSpell, error)
	CreateSpells(ctx context.Context, arg []CreateSpellsParams) *CreateSpellsBatchResults
	DeleteBeast(ctx context.Context, id pgtype.UUID) error
	DeleteClass(ctx context.Context, id pgtype.UUID) error
	DeleteClassEmbeddings(ctx context.Context, embeddingModel pgtype.Text) error
	DeleteCreatureEmbeddings(ctx context.Context, embeddingModel pgtype.Text) error
	DeleteSpecies(ctx context.Context, id pgtype.UUID) error
	DeleteSpeciesEmbeddings(ctx context.Context, embeddingModel pgtype.Text) error
	DeleteSpell(ctx context.Context, id pgtype.UUID) error
	DeleteSpellEmbeddings(ctx context.Context, embeddingModel pgtype.Text) error
	GetBeastByID(ctx context.Context, id pgtype.UUID) (ScryQuestBestiary, error)
	GetBeastByName(ctx context.Context, name string) (ScryQuestBestiary, error)
	GetClassByID(ctx context.Context, id pgtype.UUID) (ScryQuestClass, error)
	GetClassByName(ctx context.Context, name string) (ScryQuestClass, error)
	GetClassesWithoutEmbeddings(ctx context.Context) ([]GetClassesWithoutEmbeddingsRow, error)
	GetCreaturesWithoutEmbeddings(ctx context.Context) ([]GetCreaturesWithoutEmbeddingsRow, error)
	GetEmbeddingStats(ctx context.Context) ([]ScryQuestEmbeddingStat, error)
	GetSpeciesByID(ctx context.Context, id pgtype.UUID) (ScryQuestSpecy, error)
	GetSpeciesByName(ctx context.Context, name string) (ScryQuestSpecy, error)
	GetSpeciesWithoutEmbeddings(ctx context.Context) ([]GetSpeciesWithoutEmbeddingsRow, error)
	GetSpellByID(ctx context.Context, id pgtype.UUID) (ScryQuestSpell, error)
	GetSpellByName(ctx context.Context, name string) (ScryQuestSpell, error)
	GetSpellsWithoutEmbeddings(ctx context.Context) ([]GetSpellsWithoutEmbeddingsRow, error)
	ListBeasts(ctx context.Context, arg ListBeastsParams) ([]ScryQuestBestiary, error)
	ListBeastsByChallengeRating(ctx context.Context, challengeRating pgtype.Text) ([]ScryQuestBestiary, error)
	ListBeastsByType(ctx context.Context, type_ pgtype.Text) ([]ScryQuestBestiary, error)
	ListClasses(ctx context.Context, arg ListClassesParams) ([]ScryQuestClass, error)
	ListSpecies(ctx context.Context, arg ListSpeciesParams) ([]ScryQuestSpecy, error)
	ListSpells(ctx context.Context, arg ListSpellsParams) ([]ScryQuestSpell, error)
	ListSpellsByLevel(ctx context.Context, level int32) ([]ScryQuestSpell, error)
	ListSpellsBySchool(ctx context.Context, school pgtype.Text) ([]ScryQuestSpell, error)
	SearchAllContentByEmbedding(ctx context.Context, arg SearchAllContentByEmbeddingParams) ([]SearchAllContentByEmbeddingRow, error)
	SearchClassesByEmbedding(ctx context.Context, arg SearchClassesByEmbeddingParams) ([]SearchClassesByEmbeddingRow, error)
	SearchCreaturesByEmbedding(ctx context.Context, arg SearchCreaturesByEmbeddingParams) ([]SearchCreaturesByEmbeddingRow, error)
	SearchSpeciesByEmbedding(ctx context.Context, arg SearchSpeciesByEmbeddingParams) ([]SearchSpeciesByEmbeddingRow, error)
	SearchSpellsByEmbedding(ctx context.Context, arg SearchSpellsByEmbeddingParams) ([]SearchSpellsByEmbeddingRow, error)
	UpdateClassEmbedding(ctx context.Context, arg UpdateClassEmbeddingParams) error
	UpdateCreatureEmbedding(ctx context.Context, arg UpdateCreatureEmbeddingParams) error
	UpdateSpeciesEmbedding(ctx context.Context, arg UpdateSpeciesEmbeddingParams) error
	UpdateSpellEmbedding(ctx context.Context, arg UpdateSpellEmbeddingParams) error
}

var _ Querier = (*Queries)(nil)
